book:
  output-file: Engineering-Intelligent-Systems-Digital

format:
  pdf:
    classoption:
      - oneside
      - openany
      - 10.5pt
    geometry:
      - left=0.82in
      - right=0.82in
      - top=0.76in
      - bottom=0.84in
      - headheight=16pt
      - headsep=18pt
      - footskip=28pt
