format:
  pdf:
    documentclass: scrbook
    classoption:
      - open=any
    fontsize: 10.5pt
    geometry:
      - paperwidth=8.5in
      - paperheight=11in
      - top=0.76in
      - bottom=0.84in
      - inner=0.92in
      - outer=0.74in
    linestretch: 1.17
    include-in-header:
      - text: |
          \usepackage{setspace}
          \AtBeginEnvironment{verbatim}{\singlespacing}
          \usepackage{algorithm}
          \usepackage{algpseudocode}
      - print/technical-blocks.tex
      - print/preamble.tex
    toc: true
    toc-depth: 2
    number-sections: true
    colorlinks: true
    linkcolor: blue
    urlcolor: blue
    filters:
      - filters/format-numbering.lua
      - filters/technical-blocks.lua
      - filters/print-design.lua
