format:
  pdf:
    documentclass: scrbook
    fontsize: 11pt
    geometry:
      - paperwidth=8.5in
      - paperheight=11in
      - top=0.75in
      - bottom=0.75in
      - inner=0.9in
      - outer=0.6in
    linestretch: 1.15
    include-in-header:
      text: |
        \usepackage{setspace}
        \AtBeginEnvironment{verbatim}{\singlespacing}
        \usepackage{algorithm}
        \usepackage{algpseudocode}
    toc: true
    toc-depth: 3
    number-sections: true
    colorlinks: true
    linkcolor: blue
    urlcolor: blue
    filters:
      - filters/format-numbering.lua
