project:
  output-dir: output/reset/epub
book:
  output-file: Generative-AI-ORIGINAL-MANUSCRIPT
format:
  epub:
    cover-image: assets/cover/generative-ai-cover.png
    epub-metadata: styles/epub-metadata.xml
    toc: true
    toc-depth: 2
    css: styles/reset-epub.css
    epub-chapter-level: 1
