project:
  output-dir: output/epub
book:
  output-file: Generative-AI
format:
  epub:
    epub-metadata: styles/epub-metadata.xml
    toc: true
    toc-depth: 2
    css: styles/epub.css
    epub-chapter-level: 1
